name: Keep App Alive

on:
  schedule:
    - cron: '*/13 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://billing-system.onrender.com/keep-alive
      
      - name: Show timestamp
        run: |
          echo "Keep-alive ping sent at $(date)"
